handRaised/urls.py
from django.contrib import admin
from django.urls import path, include
from hrma.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', login, name='login'), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('hrma/', include('hrma.urls'))
]

hrma/urls.py
from django.urls import path

from . import views

app_name = 'hrma'
urlpatterns = [
    path('professorDashboard', views.ProfessorDashboard.as_view(), name='professorDashboard'),
    path('studentDashboard', views.StudentDasboard.as_view(), name='studentDashboard'),
    path('studentDashboard/courses/<str:course_id>/', views.CoursesView.as_view(), name='professorDashboard'),
    path('accounts/login/', views.login, name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('home', views.home, name='home'),

]

hrma/models.py
from ast import Sub
from operator import mod
from tkinter import CASCADE
from turtle import ondrag
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime


DEFAULT_COURSE_ORG_FK = 1


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_professor = models.BooleanField(default=False)
    userType = models.CharField(max_length=10, default='None')
    
    def __str__(self) -> str:
        return f'\nname: {self.username}\nemail:{self.email}\nis_student:{self.is_student}\nis_professor:{self.is_professor}'

class Organization(models.Model):
    name = models.CharField(max_length=80)
    address = models.CharField(max_length=150)
    main_owner = models.CharField(max_length=150)
    # courses = models.ForeignKey(Course, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.name 

class Subject(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=150)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.name
        
class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    organizations = models.ManyToManyField(Organization)
    subjects = models.ManyToManyField(Subject)
    # courses = models.ForeignKey(Course, on_delete=models.CASCADE)
    
class Course(models.Model):
    course_name = models.CharField(max_length=10, default=None)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    schedule = models.CharField(max_length=30)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, default=DEFAULT_COURSE_ORG_FK, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return "%s"  % (self.course_name)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    join_date = models.DateField( default=datetime.date.today)
    organizations = models.ManyToManyField(Organization)
    courses = models.ManyToManyField(Course)
    participation_score = models.IntegerField(default=0)

class Question(models.Model):
    question_title = models.CharField(max_length=40)
    question_text = models.CharField(max_length=600)
    author_by = models.ForeignKey(Student, on_delete=models.CASCADE)
    created_date = models.DateField(default= datetime.date.today)
    times_viewed = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

class QuestionComment(models.Model):
    comment_text =  models.CharField(max_length=500)
    author = models.ForeignKey(Student, on_delete=models.CASCADE)
    date_posted = models.DateField(default=datetime.date.today)
    score = models.IntegerField(default=0)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    

class Tag(models.Model):
    name = models.CharField(max_length=15)
    description = models.CharField(max_length=100)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    questions = models.ManyToManyField(Question)

class Answer(models.Model):
    answer_text = models.CharField(max_length=500)
    author_by = models.ForeignKey(Student, on_delete=models.CASCADE)
    posted_date = models.DateField(default=datetime.date.today)
    approval_professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

class AnswerComment(models.Model):
    comment_text =  models.CharField(max_length=500)
    author = models.ForeignKey(Student ,on_delete=models.CASCADE )
    date_posted = models.DateField(default=datetime.date.today)
    score = models.IntegerField(default=0)
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE)
    

hrma/forms.py
from ctypes import windll
from lib2to3.pgen2.token import LBRACE
from turtle import textinput
from django.contrib.auth.forms import UserCreationForm
from pkg_resources import require
from hrma.utlis.db import getSubjectsQuerySetListFromOrg,getSubjectsQuerySetListFromCourse
from hrma.models import Subject
from hrma.models import User
from django import forms
from hrma.models import Student, Professor, Organization, Course
from django.db.models.query import QuerySet
from itertools import chain
STUDENT = 1
PROFESSOR = 2
USER_TYPES = (
    (STUDENT, 'Student'),
    (PROFESSOR, 'Professor')
)
class SignUpForm(UserCreationForm):
    userType = forms.CharField(label='You are a: ', widget=forms.Select(choices=USER_TYPES))
    email = forms.CharField(label='Email', widget=forms.TextInput())
    password1 = forms.CharField(label='Enter password', 
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', 
                                widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2', 'userType')
        help_texts = {
            'username': None,
        }

    def save(self, commit=True):
        user = super().save()
        userType = user.userType
                
        if int(userType) == STUDENT:
            user.is_student = True
            print(f'creating student {user}')
            Student.objects.create(user=user)
        else:
            user.is_professor = True
            print(f'creating professor {user}')
            Professor.objects.create(user=user)

        if commit:
            user.save()
        return user

#----------------------------------------PROFESSOR FORMS -----------------------------------------------
class AddOrganizationToProfessor(forms.Form):
    def __init__(self, *args, **kwargs):
        super(AddOrganizationToProfessor, self).__init__(*args, **kwargs)
        self._build_fields()

    def _build_fields(self):
        orgs = Organization.objects.all()
        self.fields['organizations'] = forms.ModelChoiceField(queryset=orgs)

class AddSubjectToProfessor(forms.Form):
    def __init__(self, *args, **kwargs):
        print(kwargs)
        self.user = kwargs.pop("user")
        super(AddSubjectToProfessor, self).__init__(*args, **kwargs)
        self._build_fields()

    def _build_fields(self):
        self.professor = Professor.objects.filter(pk=self.user).first()
        print(f'professor {self.professor}')
        if self.professor.organizations:
            orgs = self.professor.organizations.all()
            self.fields['organizations'] = forms.ModelChoiceField(queryset=orgs)
            subjectsList = getSubjectsQuerySetListFromOrg(orgs)
            if len(subjectsList)>0:
                subjects = QuerySet.union(*subjectsList)
                self.fields['subjects'] = forms.ModelChoiceField(queryset=subjects)
            else:
                self.fields['subjects'] = forms.ModelChoiceField(queryset=Subject.objects.none())

class AddCourseToProfessor(AddSubjectToProfessor):
    def __init__(self, *args, **kwargs):
        print('init....')
        super(AddCourseToProfessor, self).__init__(*args, **kwargs)
        print('init.... finished')
        
    def _build_fields(self):
        super (AddCourseToProfessor,self)._build_fields()
        self.fields['course'] = forms.CharField(widget=forms.TextInput(attrs={'label':'course'}))
        
#----------------------------------------STUDENT FORMS -----------------------------------------------

class AddOrgToStudentForm(forms.Form):
    def __init__(self, *args, **kwargs):
        print('add org form init')
        super(AddOrgToStudentForm, self).__init__(*args, *kwargs)
        self._build_fields()
        print('add org form finish')
    def _build_fields(self):
        orgs = Organization.objects.all()
        self.fields['organization'] = forms.ModelChoiceField(queryset=orgs)

class AddCourseToStudentForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AddCourseToStudentForm, self).__init__(*args, **kwargs)
        self._build_fields()

    def _build_fields(self):
        student = Student.objects.filter(pk=self.user).first()
        student_orgs = student.organizations.all()
        org_courses =  Course.objects.filter(organization__in= list(student_orgs))
        print(f'student orgs {type(student_orgs)} {student_orgs}')
        print(f'orgs_classes {type(org_courses)} {org_courses}')
        self.fields['student_orgs'] = forms.ModelChoiceField(queryset=student_orgs)
        self.fields['org_courses'] = forms.ModelChoiceField(queryset=org_courses)

class PostQuestionForm(forms.Form):
    def __init__(self, *args, **kwargs) -> None:
        super(PostQuestionForm, self).__init__()
        self._build_fields()

    def _build_fields(self):
        self.fields['question_title'] = forms.CharField(widget=forms.TextInput(attrs={'class':'post_question_form_title',
                                                                                    'placeholder':'Title'}))
        self.fields['question_body'] = forms.CharField(widget=forms.Textarea(attrs={'class':'post_question_form_body',
                                                                                        'placeholder':'Body'}))
        # self.fields['questionTitle'].label = 'Title'
class PostAnswerForm(forms.Form):
    def __init__(self, *args, **kwargs) -> None:
        super(PostAnswerForm, self).__init__()
        self._build_fields()

    def _build_fields(self):
        self.fields['answer'] = forms.CharField(widget=forms.TextInput())

class PostAnswerCommentForm(forms.Form):
    def __init__(self, *args, **kwargs) -> None:
        super(PostAnswerCommentForm, self).__init__()
        self._build_fields()

    def _build_fields(self):
        self.fields['answerComment'] = forms.CharField(widget=forms.TextInput())

class PostQuestionComment(forms.Form):
    def __init__(self, *args, **kwargs) -> None:
        super(PostQuestionComment, self).__init__()
        self._build_fields()

    def _build_fields(self):
        self.fields['questionComment'] = forms.CharField(widget=forms.TextInput())



#----------------------------------------OTHER FORMS -----------------------------------------------

class AddSubject(forms.ModelForm):
    subjectName = forms.CharField(label='Subject Name', widget=forms.TextInput())
    description = forms.CharField(label='Description', widget = forms.Textarea())
    # org = forms.CharField(label='Organization', widget=forms.Select(choices=))

hrma/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login as authlogin
from django.contrib import messages
from django.views import View
from hrma.utlis.requestHelper import processProfessorPOSTRequests,processStudentPOSTRequest
from hrma.models import Question, Professor,Organization, Subject, Course, Student
from . import forms
# Create your views here
def home(request):
    return render(request, 'base.html')

class ProfessorDashboard(View):
    template_name = 'professor/home.html'
    context = {}

    def get(self, request, *args, **kwargs):
        self._build_fields(request)
        return render(request, self.template_name , self.context)
    
    def post(self, request, *args, **kwargs):
        self._processPOSTRequest(request)
        self._build_fields(request)
        return render(request, self.template_name, self.context)

    def _processPOSTRequest(self, request):
        processProfessorPOSTRequests(request)

    def _build_fields(self, request):
        print(request)
        add_org_form = forms.AddOrganizationToProfessor
        add_subject_form = forms.AddSubjectToProfessor(user=request.user)
        add_course_form = forms.AddCourseToProfessor(user=request.user)
        professor = Professor.objects.filter(pk=request.user).first()
        professor_orgs = professor.organizations.all()
        professor_subjects = professor.subjects.all()
        professor_courses = Course.objects.prefetch_related('professor__organizations').filter(professor=professor)
        print(f'professor\'s courses {professor_courses}')
        print(f'professor\'s orgs passed to template: {professor_orgs}')
        self.context = {
            'professor_courses':professor_courses,
            'professor_orgs':professor_orgs,
            'professor_subjects':professor_subjects,
            'add_course_form':add_course_form,
            'add_org_form': add_org_form,
            'add_subject_form':add_subject_form
        }
        
class StudentDasboard(View):
    template_name = 'student/home.html'
    context = {}
    def get(self, request, *args, **kwargs):
        print(f'STUDENT GET REQUEST')
        self._build_fields(request)
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        print(f'REQUEST OBJ --> {request.POST}')
        processStudentPOSTRequest(request)
        self._build_fields(request)
        return render(request, self.template_name, self.context)
        
    def _build_fields(self, request):
        student = Student.objects.filter(pk=request.user).first()
        print(f'collecting forms..')
        add_org_form = forms.AddOrgToStudentForm()
        add_course_form = forms.AddCourseToStudentForm(user = request.user)
        student_orgs = []
        student_professors = []
        student_questions = student.question_set
        student_question_comments = student.questioncomment_set
        student_answers = student.answer_set
        student_answer_comments =student.answercomment_set
        student_courses = student.courses.all()
        for course in student_courses:
            if course.organization not in student_orgs:
                student_orgs.append(course.organization)
            if course.professor not in student_professors:
                student_professors.append(course.professor)
        
        self.context = {
            'add_course_form':add_course_form,
            'add_org_form':add_org_form,
            'student_orgs':student_orgs,
            'student_courses':student_courses,
            'student_professors':student_professors,
            'student_questions' : student_questions,
            'student_question_comments' : student_question_comments,
            'student_answers' : student_answers,
            'student_answer_comments' : student_answer_comments
        }

class CoursesView(View):
    template_name = 'student/student_course.html'
    context = {}
    def get(self, request, *args, **kwargs):
        self._build_fields(request, kwargs)
        return render(request, self.template_name , self.context)

    def _build_fields(self, request, kwargs):
        course_id = kwargs.pop('course_id')
        self.context = {
            'course_id':course_id
        }     
    
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        print(f'user {user}')
        if user and user.is_active:
            authlogin(request,user)
            if user.is_professor:
                return redirect(reverse('hrma:professorDashboard')) 
            else:
                return redirect(reverse('hrma:studentDashboard')) 

        else:
            messages.error(request,'username or password not correct')
            return redirect(reverse('hrma:login'))
    else:
        form = AuthenticationForm()
    return render(request,'login.html',{'form':form})

class SignUpView(generic.CreateView):
    form_class = forms.SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

templates/hrma/professor/dashboard.html
<div class="professor-home">
    <h2>Hi Professor {{user.username}}</h2>
    <div class="sections"s>
        <!-- Org Section -->
        <section class="orgs section">
            <div class="section-header">
                <div class="orgs-section-header">
                    <h4>Your Orgs</h4> 
                </div>
                <button class="subject-add-btn add-form-btn">Add</button>
            </div>
        <div class="orgs-add-section add-form">
            <div class="add-form-content">
                <span class="close-span">X</span>
                    <h3>Join an Org</h3>
                    <form action="/hrma/professorDashboard" method="POST">
                        {% csrf_token %}
                        {{ add_org_form }}
                        <button type="submit" name="add_org_form"> Join! </button>
                    </form>
            </div>
            
        </div>
        <div class="user-subjects-list">
        </div>
        </section>

        <!-- Subject Section -->
        <section class="subjects section">
            <div class="section-header">
                <div class="subjects-section-header">
                    <h4>Your Subjects</h4> 
                </div>
                <button class="subject-add-btn add-form-btn">Add</button>
            </div>
        <div class="subject-add-section add-form">
            <div class="add-form-content">
                <span class="close-span">X</span>
                    <h3>Add a Subject</h3>
                    <form action="/hrma/professorDashboard" method="POST">
                        {% csrf_token %}
                        <label for="id_organizations">Organizations</label>
                        <select name="organization" required id="id_organizations_subjects">
                            <option value selected >--------</option>
                            {% for org in add_subject_form.organizations.field.queryset %} 
                                <option value="{{org.name}}">{{org.name}}</option> 
                            {% endfor %}
                        </select>
                        <label for="id_subjects">Subjects</label>
                        <select name="subject" required id="id_subjects">
                            <option value="{{subject.id}}" class="initialOpt" selected>------</option>

                            {% for subject in add_subject_form.subjects.field.queryset %}
                                <option value="{{subject.id}}" id="{{subject.organization}}">{{subject.name}}</option>
                            {% endfor %}
                        </select>
                        <button type="submit" name="add_subject_form"> Join! </button>
                    </form>
            </div>
            
        </div>
        <div class="user-subjects-list">
        </div>
        </section>
    </div>
                                             <!-- FILTERS -->
    <div class="filters-section">
        <div class="single-filter-section professor-orgs">
            {% for professor_org in professor_orgs %}
            <div class="single-professor-org single-filter" id="{{professor_org.name}}">
                <p>{{professor_org.name}}</p>
            </div>
            {% endfor %}
        </div>
        <div class="single-filter-section professor-subjects">
            {% for subject in professor_subjects %}
            <div class="single-professor-subject single-filter" id="{{subject.name}}">
                <p>{{subject.name}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    
                                        <!-- COURSES -->
    <section class="courses-section section">
        <div class="section-header">
            <h2>Your Courses</h2> 
            <button class="course-add-btn add-form-btn">Add</button>
        </div>
                                    <!-- COURSES-ADD-FORM -->
            <div class="course-add-section add-form" style="background-color: beige;">
                <div class="add-form-content">
                <span class="close-span">X</span>
                    <h3>Add Course</h3>
                    <form action="/hrma/professorDashboard" method="POST">
                        {% csrf_token %}
                        <label for="id_organizations">Organization</label>
                        <select name="organization" required id="id_organizations_subjects">
                            <option value selected >--------</option>
                            {% for org in add_course_form.organizations.field.queryset %} 
                                <option value="{{org.name}}">{{org.name}}</option> 
                            {% endfor %}
                        </select>
                        <label for="id_subjects">Subject</label>
                        <select name="subject" required id="id_subjects">
                            <option value="{{subject.id}}" class="initialOpt" selected>------</option>

                            {% for subject in add_course_form.subjects.field.queryset %}
                                <option value="{{subject.id}}" id="{{subject.organization}}">{{subject.name}}</option>
                            {% endfor %}
                        </select>
                        <br>
                        <div class="add-course-form-course">
                            <label for=id_course>Course</label>
                            <input type="text" name="course" label="Course" required id="id_course">
                            <br>
                            <button type="submit" name="add_course_form"> Add Course! </button>
                        </div>
                    </form>
                </div>
            </div>  
                                    <!-- COURSES-LIST   -->
        <div class="user-courses-list">
            {% for course in professor_courses %}
            <div class="single-course" id="{{course.subject.organization}}_{{course.subject}}">
                <h5>{{course.subject.organization}}</h5>
                <h4 class="course-subject">{{course.subject}}</h4>
                <h2 class="course-title">{{course.course_name}}</h2>
            </div>
            {% endfor %}
           
        </div>
    </section>
    
    
    </div>
</div>

templates/hrma/professor/home.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %} 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script> src = "{% static 'hrma.js' %}"</script>
{% endblock %}
{% block title %} Dashboard {% endblock %}
{% block content %}
{% endblock %}